### ISSUE TITLE
Error Message after processing

### ISSUE THREAD

**Issue by zenjabba** [pannal/Sub-Zero#66]
2015-11-02 12:02:27,495 - com.plexapp.agents.subzero       (-b399470) :  CRITICAL (agentkit:1057) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV)', called with guid 'com.plexapp.agents.thetvdb://74550?lang=en' (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1055, in _update
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 247, in update
    saveSubtitles(videos, subtitles)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 157, in saveSubtitles
    saveSubtitlesToMetadata(videos, subtitles)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 186, in saveSubtitlesToMetadata
    mediaPart.subtitles[Locale.Language.Match(subtitle.language.alpha2)][subtitle.page_link] = Proxy.Media(subtitle.content, ext="srt")
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 237, in __setitem__
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 220, in make_tuple
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/data.py", line 32, in sha1
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/components/data.py", line 22, in _generateHash
TypeError: must be string or buffer, not None

**Comment by pannal** [comment]
please update to the current stable by following the installation instructions, and report back if the issue persists. thanks!

**Comment by zenjabba** [comment]
2015-11-02 14:29:38,402 - com.plexapp.agents.subzero       (-bff1470) :  CRITICAL (agentkit:1057) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.3.5.273)', called with guid 'com.plexapp.agents.thetvdb://122651?lang=en' (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1055, in _update
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/__init__.py", line 212, in update
    scheduler.signal("updated_metadata", video.id)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/background.py", line 93, in signal
    if task.running:
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero.bundle/Contents/Code/support/tasks.py", line 24, in __getattribute__
    return Dict["tasks"][self.name].get(name, None)
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/code/sandbox.py", line 108, in <lambda>
KeyError: 'searchAllRecentlyAddedMissing'

This is the error I get now.

**Comment by pannal** [comment]
You haven't used any 1.3.0 beta, have you?
Please try the bleeding edge: https://github.com/pannal/Sub-Zero/archive/master.zip

**Comment by zenjabba** [comment]
2015-11-02 16:08:01,302 - com.plexapp.agents.subzero       (-c2bb470) :  ERROR (logger:27) - subliminal_patch.patch_provider_pool: Unexpected error in provider 'opensubtitles', discarding it, because of: Traceback (most recent call last):
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Libraries/Shared/subliminal_patch/patch_provider_pool.py", line 177, in list_subtitles
    provider_subtitles = self[name].list_subtitles(video, provider_languages)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Libraries/Shared/subliminal/api.py", line 62, in __getitem__
    provider.initialize()
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Libraries/Shared/subliminal_patch/patch_providers/opensubtitles.py", line 21, in initialize
    response = checked(self.server.LogIn(self.username, self.password, 'eng', 'subliminal v%s' % get_version(__version__)))
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/xmlrpclib.py", line 1224, in __call__
    return self.__send(self.__name, args)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/xmlrpclib.py", line 1578, in __request
    verbose=self.__verbose
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/xmlrpclib.py", line 1264, in request
    return self.single_request(host, handler, request_body, verbose)
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/xmlrpclib.py", line 1312, in single_request
    response.msg,
ProtocolError: <ProtocolError for api.opensubtitles.org/xml-rpc: 500 Internal Server Error>

**Comment by pannal** [comment]
That's OK, OpenSubtitles is down right now.

Original problem seems to be fixed.

**Comment by zenjabba** [comment]
Maybe I brought it down :)

**Comment by pannal** [comment]
Was your initial error after a big refresh? I've seen that error before.

**Comment by zenjabba** [comment]
Yes, a big refresh is what caused it.

**Comment by zenjabba** [comment]
Getting this error message now


2015-11-02 16:25:58,061 - com.plexapp.agents.subzero       (-bfcd470) :  CRITICAL (agentkit:1057) - Exception in the update function of agent named 'Sub-Zero Subtitles (TV, 1.3.5.273)', called with guid 'com.plexapp.agents.thetvdb://74550/7/12?lang=en' (most recent call last):
  File "bundles-release/Framework.bundle-dist/Contents/Resources/Versions/2/Python/Framework/api/agentkit.py", line 1055, in _update
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Code/__init__.py", line 207, in update
    updateLocalMedia(media, media_type=self.agent_type)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Code/__init__.py", line 178, in updateLocalMedia
    support.localmedia.findSubtitles(part)
  File "/root/Library/Plex Media Server/Plug-ins/Sub-Zero-master.bundle/Contents/Code/support/localmedia.py", line 60, in findSubtitles
    if os.path.isfile(os.path.join(path, file_path_listing)):
  File "/share/CACHEDEV1_DATA/.qpkg/PlexMediaServer/Resources/Python/lib/python2.7/genericpath.py", line 29, in isfile
    st = os.stat(path)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb2' in position 70: ordinal not in range(128)

**Comment by pannal** [comment]
Interesting. The first error may just be opensubtitles throttling you for the huge refresh. That's normal. 

The one you've just posted is new. Do your media paths have special characters?

**Comment by pannal** [comment]
Some path has a (U+00B2) in it (²)

**Comment by pannal** [comment]
I should be able to fix the path issues, though. Thanks for reporting. Will open another ticket

**Comment by pannal** [comment]
Can you pastebin the full log around the unicodedecodeerror please?
